# Generated by Django 2.0.2 on 2018-02-04 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Boards',
            },
        ),
        migrations.CreateModel(
            name='GroupBoardPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Boards')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'GroupBoardPermissions',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RD', 'Read'), ('WT', 'Write'), ('DE', 'Delete')], max_length=20)),
                ('groups', models.ManyToManyField(related_name='groups_custom', through='v1.GroupBoardPermissions', to='auth.Group')),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Boards')),
            ],
            options={
                'db_table': 'States',
            },
        ),
        migrations.CreateModel(
            name='UserBoardPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Boards')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserBoardPermissions',
            },
        ),
        migrations.AddField(
            model_name='permissions',
            name='users',
            field=models.ManyToManyField(related_name='users_custom', through='v1.UserBoardPermissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupboardpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='userboardpermissions',
            unique_together={('user', 'board', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='states',
            unique_together={('name', 'board')},
        ),
        migrations.AlterUniqueTogether(
            name='groupboardpermissions',
            unique_together={('group', 'board', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='boards',
            unique_together={('name', 'owner')},
        ),
    ]
