# Generated by Django 2.0.2 on 2018-03-15 19:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20180223_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelManagers(
            name='boards',
            managers=[
                ('permissions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='date_expired',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
