# Generated by Django 2.0.2 on 2018-03-27 20:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20180315_1915'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permissions',
            managers=[
                ('permissions', django.db.models.manager.Manager()),
            ],
        ),
    ]
