# Generated by Django 2.0.2 on 2018-05-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20180327_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupboardpermissions',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='userboardpermissions',
            options={'ordering': ('pk',)},
        ),
    ]
